---

- name: install mysql for confluence
  yum: pkg={{ item }} state=present
  with_items:
    - mysql-server

- name: start mysql server
  service: name=mysqld state=started

- name: enable mysql server
  service: name=mysqld enabled=yes

- name: add iptables rule for HTTP
  command: iptables -I INPUT -p tcp --dport 80 -j ACCEPT
  notify: save iptables rules

- name: add iptables rule for HTTPS
  command: iptables -I INPUT -p tcp --dport 443 -j ACCEPT
  notify: save iptables rules
