---

- name: set hostname
  hostname: name={{ hostname }}

- name: activate EPEL repo
  yum: name=epel-release state=present


#Standard program installations
- name: install updates
  yum: name=* state=latest

- name: install standard packages
  yum: pkg={{ item }} state=present
  with_items:
    - libselinux-python
    - clamav
    - clamd
    - logrotate
    - tmpwatch
    - ntp
    - ntpdate
    - fail2ban
    - bind-utils
    - vim
    - htop
    - tree
    - wget
    - man
    - zip
    - unzip
    - tmux
    - lsof
    - traceroute
    - gcc

- name: disable SELinux
  selinux: state=disabled
  notify: reboot server

#Configs for installed programs
- name: copy configs
  copy: owner=root group=root src={{ item.src }} dest={{ item.dest }}
  with_items:
      - {src: 'cron.daily/clamscan', dest: '/etc/cron.daily/clamscan'}
      - {src: 'cron.daily/freshclam', dest: '/etc/cron.daily/freshclam'}
      - {src: 'fail2ban/jail.conf', dest: '/etc/fail2ban/jail.conf'}
      - {src: 'sudoers', dest: '/etc/sudoers'}

#No root ssh
- name: standard ssh config
  copy: owner=root group=root src=sshd_config dest=/etc/sshd_config

- name: SSH banner
  copy: owner=root group=root src=issue dest=/etc/issue

#Regular user is passed in as an inventory variable
- name: add regular user
  user: name={{ regular_user }}  state=present

#SSH users and key variables are in the vars folder. Public keys are stored inside files folder
#Thanks to http://brokenbad.com/better-handling-of-public-ssh-keys-using-ansible/ for this solution
- name: copy ssh key for users.
  authorized_key: user={{ item.name }} key="{{ item.key }}" state=present
  with_items: ssh_users

- name: standard firewall rules with script
  script: iptables.sh

- name: enable standard services
  service: name={{item}} enabled=yes
  with_items:
      - crond
      - fail2ban
      - iptables
      - ntpd
      - sshd
      - network

#Services should be started
- name: start standard services
  service: name={{ item }} state=started
  with_items:
    - crond
    - fail2ban
    - iptables
    - ntpd
    - sshd
    - network
