---

- name: install necessary packages for mediawiki
  yum: pkg={{ item }} state=present
  with_items:
    - php-xml
    - php-pecl-apc
    - Image-Magick

#TODO: Fail2ban configuration for mediawiki to include log rotation
